accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import SignUp

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignUp.as_view(), name='signup'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from .views import PostList, PostDetail, PostCreate, PostDelete, PostUpdate

app_name = 'posts'

urlpatterns = [
    path('new', PostCreate.as_view(), name='post_create'),
    path('', PostList.as_view(), name='post_list'),
    path('<int:pk>', PostDetail.as_view(), name='post_detail'),
    path('<int:pk>/update', PostUpdate.as_view(), name='post_update'),
    path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete')
]

accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.exceptions import BadRequest
from django.db import models


def validate_input(email, password, nickname):
    if not email:
        raise BadRequest('이메일은 필수 값입니다.')
    if not password:
        raise BadRequest('비밀번호는 필수 값입니다.')
    if not nickname:
        raise BadRequest('닉네임은 필수 값입니다.')


class UserManager(BaseUserManager):
    def create_user(self, email, password, nickname):
        validate_input(email, password, nickname)
        user = self.model(email=self.normalize_email(email), nickname=nickname)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, nickname):
        validate_input(email, password, nickname)
        user = self.model(email=self.normalize_email(email), nickname=nickname)
        user.set_password(password)
        user.is_admin = True
        user.save()
        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, max_length=100)
    password = models.CharField(max_length=100)
    nickname = models.CharField(max_length=10)
    is_admin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['password', 'nickname']

    @property
    def is_superuser(self):
        return self.is_admin

    @property
    def is_staff(self):
        return self.is_admin

    object = UserManager()

    def __str__(self):
        return self.nickname

posts/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    main_image = models.ImageField(null=True, upload_to='%Y/%m')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.title

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError


class SignupForm(forms.ModelForm):
    password1 = forms.CharField(max_length=50, widget=forms.PasswordInput)
    password2 = forms.CharField(max_length=50, widget=forms.PasswordInput)

    class Meta:
        model = get_user_model()
        fields = ('email', 'password1', 'password2', 'nickname')

    def clean(self):
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            raise ValidationError('비밀번호가 같지 않습니다.')
        return super().clean()

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get('password1'))
        if commit:
            user.save()
        return user

posts/forms.py
from django.forms import ModelForm

from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'main_image')

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['main_image'].required = False

accounts/views.py
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import SignupForm


class SignUp(CreateView):
    model = get_user_model()
    form_class = SignupForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('posts:post_list')

posts/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

from .forms import PostForm
from .mixins import SuperUserRequiredMixin
from .models import Post


class PostCreate(SuperUserRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/posts-create.html'

    def get_success_url(self):
        return reverse('posts:post_detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostList(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'posts/posts-list.html'


class PostDetail(DetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'posts/posts-detail.html'


class PostUpdate(SuperUserRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/posts-update.html'

    def get_success_url(self):
        return reverse('posts:post_detail', kwargs={'pk': self.object.pk})


class PostDelete(SuperUserRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('posts:post_list')
    template_name = 'posts/post-delete.html'

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <article class="grid login-card">
        <div>
            <hgroup>
                <h1>Log in</h1>
            </hgroup>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="contrast">Login</button>
            </form>
        </div>
    </article>

    <!-- Footer -->
    <footer class="container-fluid">
        <small>Built with <a href="https://picocss.com" class="secondary">Pico</a> • <a
                href="https://github.com/picocss/examples/tree/master/sign-in/" class="secondary">Source
            code</a></small>
    </footer><!-- ./ Footer -->
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
    <article class="grid login-card">
        <div>
            <hgroup>
                <h1>Log in</h1>
            </hgroup>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="contrast">Login</button>
            </form>
        </div>
    </article>

    <!-- Footer -->
    <footer class="container-fluid">
        <small>Built with <a href="https://picocss.com" class="secondary">Pico</a> • <a
                href="https://github.com/picocss/examples/tree/master/sign-in/" class="secondary">Source
            code</a></small>
    </footer><!-- ./ Footer -->
{% endblock %}

posts/templates/posts/post-delete.html
{% extends 'base.html' %}

{% block content %}
    <h2>삭제하시겠습니까?</h2>
    <form method="post">
        {% csrf_token %}
        <button type="submit">삭제</button>
    </form>
{% endblock %}

posts/templates/posts/posts-create.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="post-form-container">
            <form action="{% url 'posts:post_create' %}" method="post" enctype="multipart/form-data">
                {{ form.as_p }}
                <button type="submit">저장</button>
                {% csrf_token %}
            </form>
        </div>
    </div>
{% endblock %}

posts/templates/posts/posts-detail.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <article class="post-detail-card">
            {% if user.is_admin %}
                <div class="edit-btn-container">
                    <a href="{% url 'posts:post_update' pk=post.pk %}">수정</a>
                    <a href="{% url 'posts:post_delete' pk=post.pk %}">삭제</a>
                </div>
            {% endif %}
            <header>
                <h1>{{ post.title }}</h1>
                <p class="author">author : {{ post.author }}</p>
            </header>
            {% if post.main_image %}
                <img src="{{ post.main_image.url }}" alt="">
            {% endif %}
            {{ post.content }}
            <footer>
                created : {{ post.created_at }}<br>
                updated : {{ post.updated_at }}
            </footer>
        </article>

    </div>
    <div id="disqus_thread" style="width: 70%; margin: 2rem auto"></div>
    <script>
        /**
         *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
         *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
        /*
        var disqus_config = function () {
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
        };
        */
        (function () { // DON'T EDIT BELOW THIS LINE
            var d = document, s = d.createElement('script');
            s.src = 'https://django-blog-16.disqus.com/embed.js';
            s.setAttribute('data-timestamp', +new Date());
            (d.head || d.body).appendChild(s);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by
        Disqus.</a></noscript>

{% endblock %}

posts/templates/posts/posts-list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        {% for post in posts %}

            <a href="{% url 'posts:post_detail' pk=post.pk %}">
                <div class="post-card">
                    <article>
                        <header>
                            {{ post.title }} <br>
                            {{ post.author }}
                        </header>
                        {% if post.main_image %}
                            <img src="{{ post.main_image.url }}" width="300">
                        {% endif %}
                        <footer>{{ post.content|truncatechars:40 }}</footer>
                    </article>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

posts/templates/posts/posts-update.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="post-forms-container">
            <form action="{% url 'posts:post_update' pk=post.pk %}" method="post" enctype="multipart/form-data">
                {{ form.as_p }}
                <button type="submit">저장</button>
                {% csrf_token %}
            </form>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="ko" data-theme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/pico-bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    <title>Blog</title>

</head>
<body>
    <nav>
        <ul>
            <li><strong><a class="main-logo" href="{% url 'posts:post_list' %}">BLOG</a></strong></li>
        </ul>
        <ul>
            {% if user.is_admin %}
                <li><a class="nav-mini-btn" href="{% url 'posts:post_create' %}">New Post</a></li>
            {% endif %}
            {% if user.is_authenticated %}
                <li><a class="nav-mini-btn" href="{% url 'accounts:logout' %}">Log Out</a></li>
            {% else %}
                <li><a class="nav-mini-btn" href="{% url 'accounts:login' %}">Log In</a></li>
            {% endif %}
            <li><a class="nav-mini-btn" href="{% url 'accounts:signup' %}">Sign Up</a></li>
        </ul>
    </nav>
    <hr>
    {% block content %}
    {% endblock %}

    <script src-="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>